// SPDX-License-Identifier: BSD-3-Clause
/* linktype.hh - LINKTYPE values */

#pragma once
#if !defined(PANKO_CAPTURE_LINKTYPE_HH)
#define PANKO_CAPTURE_LINKTYPE_HH

#include <cstdint>
#include <string_view>
#include <unordered_map>

#include "panko/internal/defs.hh"

namespace Panko::capture {
	/* NOTE(aki): This was generated using `contrib/scripts/gen_linktype_table.py` */
	enum struct linktype_t : std::uint16_t {
		BSD_LOOPBACK               = 0x0000U, /*!< BSD loopback encapsulation */
		ETHERNET                   = 0x0001U, /*!< IEEE 802.3 Ethernet */
		EXP_ETHERNET               = 0x0002U, /*!< Xerox experimental 3Mb Ethernet */
		AX25                       = 0x0003U, /*!< AX.25 layer 2 packets */
		PRONET                     = 0x0004U, /*!< Reserved for Proteon PRONet Token Ring */
		CHAOS                      = 0x0005U, /*!< Reserved for MIT Chaosnet */
		IEEE802_5                  = 0x0006U, /*!< IEEE 802.5 Token Ring */
		ARCNET_BSD                 = 0x0007U, /*!< Reserved for ARCNET Data Packets with BSD encapsulation */
		SLIP                       = 0x0008U, /*!< SLIP */
		PPP                        = 0x0009U, /*!< PPP */
		FDDI                       = 0x000AU, /*!< FDDI: per ANSI INCITS 239-1994 */
		PPP_HDLC                   = 0x0032U, /*!< PPP in HDLC-like framing */
		/* Reserved; 52-98; Do not use these values */
		PPP_ETHER                  = 0x0033U, /*!< PPPoE */
		/* not to be used; 11-49; Do not use these values */
		SYMANTEC_FIREWALL          = 0x0063U, /*!< Reserved for Symantec Enterprise Firewall */
		ATM_RFC1483                = 0x0064U, /*!< LLC/SNAP-encapsulated ATM */
		RAW                        = 0x0065U, /*!< Raw IP; begins with an IPv4 or IPv6 header */
		SLIP_BSDOS                 = 0x0066U, /*!< Reserved for BSD/OS SLIP BPF header */
		PPP_BSDOS                  = 0x0067U, /*!< Reserved for BSD/OS PPP BPF header */
		C_HDLC                     = 0x0068U, /*!< Cisco PPP with HDLC framing */
		IEEE802_11                 = 0x0069U, /*!< IEEE 802.11 wireless LAN */
		ATM_CLIP                   = 0x006AU, /*!< ATM Classical IP, with no header preceding IP */
		FRELAY                     = 0x006BU, /*!< Frame Relay LAPF frames */
		LOOP                       = 0x006CU, /*!< OpenBSD loopback encapsulation */
		ENC                        = 0x006DU, /*!< Reserved for OpenBSD IPSEC encapsulation */
		LANE8023                   = 0x006EU, /*!< Reserved for ATM LANE + 802.3 */
		HIPPI                      = 0x006FU, /*!< Reserved for NetBSD HIPPI */
		HDLC                       = 0x0070U, /*!< Reserved for NetBSD HDLC framing */
		LINUX_SLL                  = 0x0071U, /*!< Linux cooked capture encapsulation */
		LTALK                      = 0x0072U, /*!< Apple LocalTalk */
		ECONET                     = 0x0073U, /*!< Reserved for Acorn Econet */
		IPFILTER                   = 0x0074U, /*!< Reserved for OpenBSD ipfilter */
		PFLOG                      = 0x0075U, /*!< OpenBSD pflog; struct pfloghdr structure */
		CISCO_IOS                  = 0x0076U, /*!< Reserved for Cisco-internal use */
		IEEE802_11_PRISM           = 0x0077U, /*!< Prism monitor mode */
		IEEE802_11_AIRONET         = 0x0078U, /*!< Reserved for 802.11 + FreeFreeBSD Aironet radio metadata */
		HHDLC                      = 0x0079U, /*!< Reserved for Siemens HiPath HDLC */
		IP_OVER_FC                 = 0x007AU, /*!< IP-over-Fibre Channel, starting with the Network_Header */
		SUNATM                     = 0x007BU, /*!< ATM traffic captured from a SunATM device */
		RIO                        = 0x007CU, /*!< Reserved for RapidIO */
		PCI_EXP                    = 0x007DU, /*!< Reserved for PCI Express */
		AURORA                     = 0x007EU, /*!< Reserved for Xilinx Aurora link layer */
		IEEE802_11_RADIOTAP        = 0x007FU, /*!< Radiotap header, followed by an 802.11 header */
		TZSP                       = 0x0080U, /*!< Reserved for Tazmen Sniffer Protocol */
		ARCNET_LINUX               = 0x0081U, /*!< Reserved for ARCNET Data Packets with Linux encapsulation */
		JUNIPER_MLPPP              = 0x0082U, /*!< Reserved for Juniper Networks */
		JUNIPER_MLFR               = 0x0083U, /*!< Reserved for Juniper Networks */
		JUNIPER_ES                 = 0x0084U, /*!< Reserved for Juniper Networks */
		JUNIPER_GGSN               = 0x0085U, /*!< Reserved for Juniper Networks */
		JUNIPER_MFR                = 0x0086U, /*!< Reserved for Juniper Networks */
		JUNIPER_ATM2               = 0x0087U, /*!< Reserved for Juniper Networks */
		JUNIPER_SERVICES           = 0x0088U, /*!< Reserved for Juniper Networks */
		JUNIPER_ATM1               = 0x0089U, /*!< Reserved for Juniper Networks */
		APPLE_IP_OVER_IEEE1394     = 0x008AU, /*!< Apple IP-over-IEEE 1394 cooked header */
		MTP2_WITH_PHDR             = 0x008BU, /*!< Signaling System 7 (SS7) Message Transfer Part Level */
		MTP2                       = 0x008CU, /*!< SS7 Level 2 */
		MTP3                       = 0x008DU, /*!< SS7 Level 3, with no MTP2 header */
		SCCP                       = 0x008EU, /*!< SS7 Control Part, with no MTP3 or MTP2 header */
		DOCSIS                     = 0x008FU, /*!< DOCSIS MAC frames */
		LINUX_IRDA                 = 0x0090U, /*!< Linux-IrDA packets */
		IBM_SP                     = 0x0091U, /*!< Reserved for IBM SP switch */
		IBM_SN                     = 0x0092U, /*!< Reserved for IBM Next Federation switch */
		RESERVED_01                = 0x0093U, /*!< For private use (deprecated) */
		RESERVED_02                = 0x0094U, /*!< For private use (deprecated) */
		RESERVED_03                = 0x0095U, /*!< For private use (deprecated) */
		RESERVED_04                = 0x0096U, /*!< For private use (deprecated) */
		RESERVED_05                = 0x0097U, /*!< For private use (deprecated) */
		RESERVED_06                = 0x0098U, /*!< For private use (deprecated) */
		RESERVED_07                = 0x0099U, /*!< For private use (deprecated) */
		RESERVED_08                = 0x009AU, /*!< For private use (deprecated) */
		RESERVED_09                = 0x009BU, /*!< For private use (deprecated) */
		RESERVED_10                = 0x009CU, /*!< For private use (deprecated) */
		RESERVED_11                = 0x009DU, /*!< For private use (deprecated) */
		RESERVED_12                = 0x009EU, /*!< For private use (deprecated) */
		RESERVED_13                = 0x009FU, /*!< For private use (deprecated) */
		RESERVED_14                = 0x00A0U, /*!< For private use (deprecated) */
		RESERVED_15                = 0x00A1U, /*!< For private use (deprecated) */
		RESERVED_16                = 0x00A2U, /*!< For private use (deprecated) */
		IEEE802_11_AVS             = 0x00A3U, /*!< AVS header, followed by an 802.11 header */
		JUNIPER_MONITOR            = 0x00A4U, /*!< Reserved for Juniper Networks */
		BACNET_MS_TP               = 0x00A5U, /*!< BACnet MS/TP frames */
		PPP_PPPD                   = 0x00A6U, /*!< PPP in HDLC-like encapsulation, like LINKTYPE_PPP_HDLC, different stuffing */
		JUNIPER_PPPOE              = 0x00A7U, /*!< Reserved for Juniper Networks */
		JUNIPER_PPPOE_ATM          = 0x00A8U, /*!< Reserved for Juniper Networks */
		GPRS_LLC                   = 0x00A9U, /*!< General Packet Radio Service Logical Link Control, as per 3GPP TS 04.64 */
		GPF_T                      = 0x00AAU, /*!< Transparent-mapped generic framing procedure */
		GPF_F                      = 0x00ABU, /*!< Frame-mapped generic framing procedure */
		GCOM_T1E1                  = 0x00ACU, /*!< Reserved for Gcom T1/E1 line monitoring equipment */
		GCOM_SERIAL                = 0x00ADU, /*!< Reserved for Gcom T1/E1 line monitoring equipment */
		JUNIPER_PIC_PEER           = 0x00AEU, /*!< Reserved for Juniper Networks */
		ERF_ETH                    = 0x00AFU, /*!< Endace ERF header followed by 802.3 Ethernet */
		ERF_POS                    = 0x00B0U, /*!< Endace ERF header followed by Packet-over-SONET */
		LINUX_LAPD                 = 0x00B1U, /*!< Linux vISDN LAPD frames */
		JUNIPER_ETHER              = 0x00B2U, /*!< Reserved for Juniper Networks */
		JUNIPER_PPP                = 0x00B3U, /*!< Reserved for Juniper Networks */
		JUNIPER_FRELAY             = 0x00B4U, /*!< Reserved for Juniper Networks */
		JUNIPER_CHDLC              = 0x00B5U, /*!< Reserved for Juniper Networks */
		MFR                        = 0x00B6U, /*!< FRF.16.1 Multi-Link Frame Relay frames, beginning with an FRF.12 Interface fragmentation format fragmentation header */
		JUNIPER_VP                 = 0x00B7U, /*!< Reserved for Juniper Networks */
		A429                       = 0x00B8U, /*!< Reserved for ARINC 429 frames */
		A653_ICM                   = 0x00B9U, /*!< Reserved for Arinc 653 Interpartition Communication messages */
		USB_FREEBSD                = 0x00BAU, /*!< USB packets, beginning with a FreeBSD USB header */
		BLUETOOTH_HCI_H4           = 0x00BBU, /*!< Bluetooth HCI UART transport layer; the frame contains an HCI packet indicator octet, as specified by the UART Transport Layer portion of the most recent Bluetooth Core specification, followed by an HCI packet of the specified packet type, as specified by the Host Controller Interface Functional Specification portion of the most recent Bluetooth Core Specification */
		IEEE802_16_MAC_CPS         = 0x00BCU, /*!< Reserved for IEEE 802.16 MAC Common Part Sublayer */
		USB_LINUX                  = 0x00BDU, /*!< USB packets, beginning with a Linux USB header, as specified by the struct usbmon_packet in the Documentation/usb/usbmon.txt file in the Linux source tree. Only the first 48 octets of that header are present. All fields in the header are in host byte order. When performing a live capture, the host byte order is the byte order of the machine on which the packets are captured. When reading a PCAP file, the byte order is the byte order for the file, as specified by the file's magic number; when reading a PCAPNG file, the byte order is the byte order for the section of the PCAPNG file, as specified by the Section Header Block */
		CAN20B                     = 0x00BEU, /*!< Reserved for Controller Area Network (CAN) v. 2.0B packets */
		IEEE802_15_4_LINUX         = 0x00BFU, /*!< IEEE 802.15.4, with address fields padded, as is done by Linux drivers */
		PPI                        = 0x00C0U, /*!< Per-Packet Information information, as specified by the Per-Packet Information Header Specification , followed by a packet with the LINKTYPE_ value specified by the pph_dlt field of that header */
		IEEE802_16_MAC_CPS_RADIO   = 0x00C1U, /*!< Reserved for 802.16 MAC Common Part Sublayer plus radio header */
		JUNIPER_ISM                = 0x00C2U, /*!< Reserved for Juniper Networks */
		IEEE802_15_4_WITHFCS       = 0x00C3U, /*!< IEEE 802.15.4 Low-Rate Wireless Networks, with each packet having the FCS at the end of the frame */
		SITA                       = 0x00C4U, /*!< Various link-layer types, with a pseudo-header */
		ERF                        = 0x00C5U, /*!< Endace ERF records */
		RAIF1                      = 0x00C6U, /*!< Reserved for Ethernet packets captured from a u10 Networks board */
		IPMB_KONTRON               = 0x00C7U, /*!< Reserved for IPMB packet for IPMI, with a 2-octet header */
		JUNIPER_ST                 = 0x00C8U, /*!< Reserved for Juniper Networks */
		BLUETOOTH_HCI_H4_WITH_PHDR = 0x00C9U, /*!< Bluetooth HCI UART transport layer; the frame contains a 4-octet direction field, in network byte order (big-endian), the low-order bit of which is set if the frame was sent from the host to the controller and clear if the frame was received by the host from the controller, followed by an HCI packet indicator octet, as specified by the UART Transport Layer portion of the most recent Bluetooth Core specification, followed by an HCI packet of the specified packet type, as specified by the Host Controller Interface Functional Specification portion of the most recent Bluetooth Core Specification */
		AX25_KISS                  = 0x00CAU, /*!< AX.25 packet, with a KISS header */
		LAPD                       = 0x00CBU, /*!< Link Access Procedures on the D Channel (LAPD) frames, starting with the address field, with no pseudo-header */
		PPP_WITH_DIR               = 0x00CCU, /*!< PPP, as per RFC 1661 and RFC 1662 , preceded with a one-octet pseudo-header with a zero value meaning received by this host and a non-zero value meaning sent by this host; if the first 2 octets are 0xff and 0x03, it's PPP in HDLC-like framing, with the PPP header following those two octets, otherwise it's PPP without framing, and the packet begins with the PPP header. The data in the frame is not octet-stuffed or bit-stuffed */
		C_HDLC_WITH_DIR            = 0x00CDU, /*!< Cisco PPP with HDLC framing, preceded with a one-octet pseudo-header with a zero value meaning received by this host and a non-zero value meaning sent by this host */
		FRELAY_WITH_DIR            = 0x00CEU, /*!< Frame Relay LAPF frames, beginning with a one-octet pseudo-header with a zero value meaning received by this host (DCE->DTE) and a non-zero value meaning sent by this host (DTE->DCE), followed by an ITU-T Recommendation Q.922 LAPF header starting with the address field, and without an FCS at the end of the frame */
		LAPB_WITH_DIR              = 0x00CFU, /*!< Link Access Procedure, Balanced (LAPB), as specified by ITU-T Recommendation X.25 , preceded with a one-octet pseudo-header with a zero value meaning received by this host (DCE->DTE) and a non-zero value meaning sent by this host (DTE->DCE) */
		Reserved                   = 0x00D0U, /*!< Reserved for an unspecified link-layer type */
		I2C_LINUX                  = 0x00D1U, /*!< Linux I2C packets */
		FLEXRAY                    = 0x00D2U, /*!< FlexRay frames or symbols, with a pseudo-header */
		MOST                       = 0x00D3U, /*!< Reserved for Media Oriented Systems Transport (MOST) bus */
		LIN                        = 0x00D4U, /*!< Local Interconnect Network (LIN) automotive bus */
		X2E_SERIAL                 = 0x00D5U, /*!< Reserved for X2E serial line captures */
		X2E_XORAYA                 = 0x00D6U, /*!< Reserved for X2E Xoraya data loggers */
		IEEE802_15_4_NONASK_PHY    = 0x00D7U, /*!< IEEE 802.15.4 Low-Rate Wireless Networks, with each packet having the FCS at the end of the frame, and with the PHY-level data for the O-QPSK, BPSK, GFSK, MSK, and RCC DSS BPSK PHYs (4 octets of 0 as preamble, one octet of SFD, one octet of frame length + reserved bit) preceding the MAC-layer data (starting with the frame control field) */
		LINUX_EVDEV                = 0x00D8U, /*!< Reserved for Linux evdev messages */
		GSMTAP_UM                  = 0x00D9U, /*!< Reserved for GSM Um interface, with gsmtap header */
		GSMTAP_ABIS                = 0x00DAU, /*!< Reserved for GSM Abis interface, with gsmtap header */
		MPLS                       = 0x00DBU, /*!< MPLS packets with MPLS label as the header */
		USB_LINUX_MMAPPED          = 0x00DCU, /*!< USB packets, beginning with a Linux USB header, as specified by the struct usbmon_packet in the Documentation/usb/usbmon.txt file in the Linux source tree. All 64 octets of the header are present. All fields in the header are in host byte order. When performing a live capture, the host byte order is the byte order of the machine on which the packets are captured. When reading a PCAP file, the byte order is the byte order for the file, as specified by the file's magic number; when reading a PCAPNG file, the byte order is the byte order for the section of the PCAPNG file, as specified by the Section Header Block. For isochronous transfers, the ndesc field specifies the number of isochronous descriptors that follow */
		DECT                       = 0x00DDU, /*!< Reserved for DECT packets, with a pseudo-header */
		AOS                        = 0x00DEU, /*!< Reserved for OS Space Data Link Protocol */
		WIHART                     = 0x00DFU, /*!< Reserved for Wireless HART (Highway Addressable Remote Transducer) */
		FC_2                       = 0x00E0U, /*!< Fibre Channel FC-2 frames, beginning with a Frame_Header */
		FC_2_WITH_FRAME_DELIMS     = 0x00E1U, /*!< Fibre Channel FC-2 frames, beginning an encoding of the SOF, followed by a Frame_Header, and ending with an encoding of the SOF. The encodings represent the frame delimiters as 4-octet sequences representing the corresponding ordered sets, with K28.5 represented as 0xBC, and the D symbols as the corresponding octet values; for example, SOFi2, which is K28.5 - D21.5 - D1.2 - D21.2, is represented as 0xBC 0xB5 0x55 0x55 */
		IPNET                      = 0x00E2U, /*!< Solaris ipnet */
		CAN_SOCKETCAN              = 0x00E3U, /*!< Controller Area Network frames */
		IPV4                       = 0x00E4U, /*!< Raw IPv4; the packet begins with an IPv4 header */
		IPV6                       = 0x00E5U, /*!< Raw IPv6; the packet begins with an IPv6 header */
		IEEE802_15_4_NOFCS         = 0x00E6U, /*!< IEEE 802.15.4 Low-Rate Wireless Network, without the FCS at the end of the frame */
		DBUS                       = 0x00E7U, /*!< Raw D-Bus messages , starting with the endianness flag, followed by the message type, etc., but without the authentication handshake before the message sequence */
		JUNIPER_VS                 = 0x00E8U, /*!< Reserved for Juniper Networks */
		JUNIPER_SRX_E2E            = 0x00E9U, /*!< Reserved for Juniper Networks */
		JUNIPER_FIBRECHANNEL       = 0x00EAU, /*!< Reserved for Juniper Networks */
		DVB_CI                     = 0x00EBU, /*!< DVB-CI messages */
		MUX27010                   = 0x00ECU, /*!< Variant of 3GPP TS 27.010 multiplexing protocol */
		STANAG_5066_D_PDU          = 0x00EDU, /*!< D_PDUs as described by NATO standard STANAG 5066, starting with the synchronization sequence, and including both header and data CRCs. The current version of STANAG 5066 is backwards-compatible with the 1.0.2 version , although newer versions are classified */
		JUNIPER_ATM_CEMIC          = 0x00EEU, /*!< Reserved for Juniper Networks */
		NFLOG                      = 0x00EFU, /*!< Linux netlink NETLINK NFLOG socket log messages */
		NETANALYZER                = 0x00F0U, /*!< Ethernet frames with netANALYZER pseudo-header */
		NETANALYZER_TRANSPARENT    = 0x00F1U, /*!< Ethernet frames with netANALYZER pseudo-header, preamble, and SFD */
		IPOIB                      = 0x00F2U, /*!< IP-over-InfiniBand */
		MPEG_2_TS                  = 0x00F3U, /*!< MPEG-2 Transport Stream transport packets */
		NG40                       = 0x00F4U, /*!< Frames from ng4T GmbH's ng40 protocol tester */
		NFC_LLCP                   = 0x00F5U, /*!< NFC Logical Link Control Protocol frames, with a pseudo-header */
		PFSYNC                     = 0x00F6U, /*!< Reserved for pfsync output */
		INFINIBAND                 = 0x00F7U, /*!< Raw InfiniBand frames, starting with the Local Routing Header, as specified in Chapter 5 Data packet format of InfiniBand™ Architectural Specification Release 1.2.1 Volume 1 - General Specifications */
		SCTP                       = 0x00F8U, /*!< SCTP packets, as defined by RFC 4960 , with no lower-level protocols such as IPv4 or IPv6 */
		USBPCAP                    = 0x00F9U, /*!< USB packets, beginning with a USBPcap header */
		RTAC_SERIAL                = 0x00FAU, /*!< Serial-line packet from the Schweitzer Engineering Laboratories RTAC product */
		BLUETOOTH_LE_LL            = 0x00FBU, /*!< Bluetooth Low Energy air interface Link Layer packets, in the format described in Section 2.1 (PACKET FORMAT) of volume 6 of the Bluetooth Specification Version 4.0 (see PDF page 2200), but without the Preamble */
		WIRESHARK_UPPER_PDU        = 0x00FCU, /*!< Reserved for Wireshark */
		NETLINK                    = 0x00FDU, /*!< Linux Netlink capture encapsulation */
		BLUETOOTH_LINUX_MONITOR    = 0x00FEU, /*!< Bluetooth Linux Monitor */
		BLUETOOTH_BREDR_BB         = 0x00FFU, /*!< Bluetooth Basic Rate and Enhanced Data Rate baseband packets */
		BLUETOOTH_LE_LL_WITH_PHDR  = 0x0100U, /*!< Bluetooth Low Energy link-layer packets */
		PROFIBUS_DL                = 0x0101U, /*!< PROFIBUS data link layer packets, as specified by IEC standard 61158-4-3, beginning with the start delimiter, ending with the end delimiter, and including all octets between them */
		PKTAP                      = 0x0102U, /*!< Apple PKTAP capture encapsulation */
		EPON                       = 0x0103U, /*!< Ethernet-over-passive-optical-network packets, starting with the last 6 octets of the modified preamble as specified by 65.1.3.2 Transmit in Clause 65 of Section 5 of IEEE 802.3, followed immediately by an Ethernet frame */
		IPMI_HPM_2                 = 0x0104U, /*!< IPMI trace packets, as specified by Table 3-20 Trace Data Block Format in the PICMG HPM.2 specification The timestamps for packets in this format must match the timestamps in the Trace Data Blocks */
		ZWAVE_R1_R2                = 0x0105U, /*!< Z-Wave RF profile R1 and R2 packets */
		ZWAVE_R3                   = 0x0106U, /*!< Z-Wave RF profile R3 packets */
		WATTSTOPPER_DLM            = 0x0107U, /*!< WattStopper Digital Lighting Management (DLM) and Legrand Nitoo Open protocol packets */
		ISO_14443                  = 0x0108U, /*!< ISO 14443 contactless smartcard messages */
		RDS                        = 0x0109U, /*!< IEC 62106 Radio data system (RDS) groups */
		USB_DARWIN                 = 0x010AU, /*!< USB packets captured on a Darwin-based operating system (macOS, etc.) */
		OPENFLOW                   = 0x010BU, /*!< Reserved for OpenBSD DLT_OPENFLOW */
		SDLC                       = 0x010CU, /*!< SDLC packets, as specified by Chapter 1, DLC Links, section Synchronous Data Link Control (SDLC) of Systems Network Architecture Formats, GA27-3136-20 , without the flag fields, zero-bit insertion, or Frame Check Sequence field, containing SNA path information units (PIUs) as the payload */
		TI_LLN_SNIFFER             = 0x010DU, /*!< Reserved for Texas Instruments protocol sniffer */
		LORATAP                    = 0x010EU, /*!< LoRaTap pseudo-header , followed by the payload, which is typically the PHYPayload from the LoRaWan specification */
		VSOCK                      = 0x010FU, /*!< Protocol for communication between host and guest machines in VMware and KVM hypervisors */
		NORDIC_BLE                 = 0x0110U, /*!< Messages to and from a Nordic Semiconductor nRF Sniffer for Bluetooth LE packets */
		DOCSIS31_XRA31             = 0x0111U, /*!< DOCSIS packets and bursts, preceded by a pseudo-header */
		ETHERNET_MPACKET           = 0x0112U, /*!< mPackets, as specified by IEEE 802.3br Figure 99-4, starting with the preamble and always ending with a CRC field */
		DISPLAYPORT_AUX            = 0x0113U, /*!< DisplayPort AUX channel monitoring messages */
		LINUX_SLL2                 = 0x0114U, /*!< Linux cooked capture encapsulation v2 */
		SERCOS_MONITOR             = 0x0115U, /*!< Reserved for Sercos Monitor */
		OPENVIZSLA                 = 0x0116U, /*!< OpenVizsla FPGA-based USB sniffer */
		EBHSCR                     = 0x0117U, /*!< Elektrobit High Speed Capture and Replay (EBHSCR) format */
		VPP_DISPATCH               = 0x0118U, /*!< fd.io VPP graph dispatcher trace records */
		DSA_TAG_BRCM               = 0x0119U, /*!< Ethernet frames, with a Broadcom switch tag inserted */
		DSA_TAG_BRCM_PREPEND       = 0x011AU, /*!< Ethernet frames, with a Broadcom switch tag prepended */
		IEEE802_15_4_TAP           = 0x011BU, /*!< IEEE 802.15.4 Low-Rate Wireless Networks, with a pseudo-header containing TLVs with metadata preceding the 802.15.4 header */
		DSA_TAG_DSA                = 0x011CU, /*!< Ethernet frames, with a Marvell DSA switch tag inserted */
		DSA_TAG_EDSA               = 0x011DU, /*!< Ethernet frames, with a Marvell EDSA switch tag inserted */
		ELEE                       = 0x011EU, /*!< Payload of lawful intercept packets using the ELEE protocol The packet begins with the ELEE header; it does not include any transport-layer or lower-layer headers for protocols used to transport ELEE packets */
		Z_WAVE_SERIAL              = 0x011FU, /*!< Serial frames transmitted between a host and a Z-Wave chip over an RS-232 or USB serial connection */
		USB_2_0                    = 0x0120U, /*!< USB 2.0, 1.1, or 1.0 packet, beginning with a PID, as described by Chapter 8 Protocol Layer of the the Universal Serial Bus Specification Revision 2.0 */
		ATSC_ALP                   = 0x0121U, /*!< ATSC Link-Layer Protocol frames, as described in section 5 of the A/330 Link-Layer Protocol specification, found at https://www.atsc.org/atsc-documents/type/3-0-standards/, beginning with a Base Header */
		ETW                        = 0x0122U, /*!< Event Tracing for Windows messages */
		NETANALYZER_NG             = 0x0123U, /*!< Reserved for Hilscher Gesellschaft fuer Systemautomation mbH netANALYZER NG hardware and software */
		ZBOSS_NCP                  = 0x0124U, /*!< ZBOSS NCP Serial Protocol, with a pseudo-header */
		USB_2_0_LOW_SPEED          = 0x0125U, /*!< Low-Speed USB 2.0, 1.1, or 1.0 packet, beginning with a PID, as described by Chapter 8 Protocol Layer of the https://www.usb.org/document-library/usb-20-specification the Universal Serial Bus Specification Revision 2.0 */
		USB_2_0_FULL_SPEED         = 0x0126U, /*!< Full-Speed USB 2.0, 1.1, or 1.0 packet, beginning with a PID, as described by Chapter 8 Protocol Layer of the https://www.usb.org/document-library/usb-20-specification the Universal Serial Bus Specification Revision 2.0 */
		USB_2_0_HIGH_SPEED         = 0x0127U, /*!< High-Speed USB 2.0 packet, beginning with a PID, as described by Chapter 8 Protocol Layer of the https://www.usb.org/document-library/usb-20-specification the Universal Serial Bus Specification Revision 2.0 */
		AUERSWALD_LOG              = 0x0128U, /*!< Auerswald Logger Protocol, as described in https://github.com/Auerswald-GmbH/auerlog/blob/master/auerlog.txt */
		ZWAVE_TAP                  = 0x0129U, /*!< Z-Wave packets, as specified by ITU-T Recommendation G.9959, with a https://gitlab.com/exegin/zwave-g9959-tap TAP meta-data header */
		SILABS_DEBUG_CHANNEL       = 0x012AU, /*!< Silicon Labs debug channel protocol, as described in https://github.com/SiliconLabs/java_packet_trace_library/blob/master/doc/debug-channel.md */
		FIRA_UCI                   = 0x012BU, /*!< Ultra-wideband (UWB) controller interface protocol (UCI) */
		MDB                        = 0x012CU, /*!< MDB (Multi-Drop Bus) protocol between a vending machine controller and peripherals inside the vending machine, with the message format specified by https://www.kaiser.cx/pcap-mdb.html the PCAP format for MDB specification */
		DECT_NR                    = 0x012DU, /*!< DECT-2020 New Radio (NR) MAC layer specified in https://www.etsi.org/committee/1394-dect ETSI TS 103 636-4. The Physical Header Field is always encoded using 80 bits (10 bytes). Broadcast transmissions using 40 bits (5 bytes) is padded with 40 zero bits (5 bytes). When padding is used the Receiver Identity value 0x0000 (reserved address) is used to detect broadcast transmissions */
		PRIVATE_USE_BEG            = 0xFDE9U, /*!< Beginning of private use range */
		PRIVATE_USE_000            = 0xFDE9U, /*!< Reserved for private use */
		PRIVATE_USE_001            = 0xFDEAU, /*!< Reserved for private use */
		PRIVATE_USE_002            = 0xFDEBU, /*!< Reserved for private use */
		PRIVATE_USE_003            = 0xFDECU, /*!< Reserved for private use */
		PRIVATE_USE_004            = 0xFDEDU, /*!< Reserved for private use */
		PRIVATE_USE_005            = 0xFDEEU, /*!< Reserved for private use */
		PRIVATE_USE_006            = 0xFDEFU, /*!< Reserved for private use */
		PRIVATE_USE_007            = 0xFDF0U, /*!< Reserved for private use */
		PRIVATE_USE_008            = 0xFDF1U, /*!< Reserved for private use */
		PRIVATE_USE_009            = 0xFDF2U, /*!< Reserved for private use */
		PRIVATE_USE_010            = 0xFDF3U, /*!< Reserved for private use */
		PRIVATE_USE_011            = 0xFDF4U, /*!< Reserved for private use */
		PRIVATE_USE_012            = 0xFDF5U, /*!< Reserved for private use */
		PRIVATE_USE_013            = 0xFDF6U, /*!< Reserved for private use */
		PRIVATE_USE_014            = 0xFDF7U, /*!< Reserved for private use */
		PRIVATE_USE_015            = 0xFDF8U, /*!< Reserved for private use */
		PRIVATE_USE_016            = 0xFDF9U, /*!< Reserved for private use */
		PRIVATE_USE_017            = 0xFDFAU, /*!< Reserved for private use */
		PRIVATE_USE_018            = 0xFDFBU, /*!< Reserved for private use */
		PRIVATE_USE_019            = 0xFDFCU, /*!< Reserved for private use */
		PRIVATE_USE_020            = 0xFDFDU, /*!< Reserved for private use */
		PRIVATE_USE_021            = 0xFDFEU, /*!< Reserved for private use */
		PRIVATE_USE_022            = 0xFDFFU, /*!< Reserved for private use */
		PRIVATE_USE_023            = 0xFE00U, /*!< Reserved for private use */
		PRIVATE_USE_024            = 0xFE01U, /*!< Reserved for private use */
		PRIVATE_USE_025            = 0xFE02U, /*!< Reserved for private use */
		PRIVATE_USE_026            = 0xFE03U, /*!< Reserved for private use */
		PRIVATE_USE_027            = 0xFE04U, /*!< Reserved for private use */
		PRIVATE_USE_028            = 0xFE05U, /*!< Reserved for private use */
		PRIVATE_USE_029            = 0xFE06U, /*!< Reserved for private use */
		PRIVATE_USE_030            = 0xFE07U, /*!< Reserved for private use */
		PRIVATE_USE_031            = 0xFE08U, /*!< Reserved for private use */
		PRIVATE_USE_032            = 0xFE09U, /*!< Reserved for private use */
		PRIVATE_USE_033            = 0xFE0AU, /*!< Reserved for private use */
		PRIVATE_USE_034            = 0xFE0BU, /*!< Reserved for private use */
		PRIVATE_USE_035            = 0xFE0CU, /*!< Reserved for private use */
		PRIVATE_USE_036            = 0xFE0DU, /*!< Reserved for private use */
		PRIVATE_USE_037            = 0xFE0EU, /*!< Reserved for private use */
		PRIVATE_USE_038            = 0xFE0FU, /*!< Reserved for private use */
		PRIVATE_USE_039            = 0xFE10U, /*!< Reserved for private use */
		PRIVATE_USE_040            = 0xFE11U, /*!< Reserved for private use */
		PRIVATE_USE_041            = 0xFE12U, /*!< Reserved for private use */
		PRIVATE_USE_042            = 0xFE13U, /*!< Reserved for private use */
		PRIVATE_USE_043            = 0xFE14U, /*!< Reserved for private use */
		PRIVATE_USE_044            = 0xFE15U, /*!< Reserved for private use */
		PRIVATE_USE_045            = 0xFE16U, /*!< Reserved for private use */
		PRIVATE_USE_046            = 0xFE17U, /*!< Reserved for private use */
		PRIVATE_USE_047            = 0xFE18U, /*!< Reserved for private use */
		PRIVATE_USE_048            = 0xFE19U, /*!< Reserved for private use */
		PRIVATE_USE_049            = 0xFE1AU, /*!< Reserved for private use */
		PRIVATE_USE_050            = 0xFE1BU, /*!< Reserved for private use */
		PRIVATE_USE_051            = 0xFE1CU, /*!< Reserved for private use */
		PRIVATE_USE_052            = 0xFE1DU, /*!< Reserved for private use */
		PRIVATE_USE_053            = 0xFE1EU, /*!< Reserved for private use */
		PRIVATE_USE_054            = 0xFE1FU, /*!< Reserved for private use */
		PRIVATE_USE_055            = 0xFE20U, /*!< Reserved for private use */
		PRIVATE_USE_056            = 0xFE21U, /*!< Reserved for private use */
		PRIVATE_USE_057            = 0xFE22U, /*!< Reserved for private use */
		PRIVATE_USE_058            = 0xFE23U, /*!< Reserved for private use */
		PRIVATE_USE_059            = 0xFE24U, /*!< Reserved for private use */
		PRIVATE_USE_060            = 0xFE25U, /*!< Reserved for private use */
		PRIVATE_USE_061            = 0xFE26U, /*!< Reserved for private use */
		PRIVATE_USE_062            = 0xFE27U, /*!< Reserved for private use */
		PRIVATE_USE_063            = 0xFE28U, /*!< Reserved for private use */
		PRIVATE_USE_064            = 0xFE29U, /*!< Reserved for private use */
		PRIVATE_USE_065            = 0xFE2AU, /*!< Reserved for private use */
		PRIVATE_USE_066            = 0xFE2BU, /*!< Reserved for private use */
		PRIVATE_USE_067            = 0xFE2CU, /*!< Reserved for private use */
		PRIVATE_USE_068            = 0xFE2DU, /*!< Reserved for private use */
		PRIVATE_USE_069            = 0xFE2EU, /*!< Reserved for private use */
		PRIVATE_USE_070            = 0xFE2FU, /*!< Reserved for private use */
		PRIVATE_USE_071            = 0xFE30U, /*!< Reserved for private use */
		PRIVATE_USE_072            = 0xFE31U, /*!< Reserved for private use */
		PRIVATE_USE_073            = 0xFE32U, /*!< Reserved for private use */
		PRIVATE_USE_074            = 0xFE33U, /*!< Reserved for private use */
		PRIVATE_USE_075            = 0xFE34U, /*!< Reserved for private use */
		PRIVATE_USE_076            = 0xFE35U, /*!< Reserved for private use */
		PRIVATE_USE_077            = 0xFE36U, /*!< Reserved for private use */
		PRIVATE_USE_078            = 0xFE37U, /*!< Reserved for private use */
		PRIVATE_USE_079            = 0xFE38U, /*!< Reserved for private use */
		PRIVATE_USE_080            = 0xFE39U, /*!< Reserved for private use */
		PRIVATE_USE_081            = 0xFE3AU, /*!< Reserved for private use */
		PRIVATE_USE_082            = 0xFE3BU, /*!< Reserved for private use */
		PRIVATE_USE_083            = 0xFE3CU, /*!< Reserved for private use */
		PRIVATE_USE_084            = 0xFE3DU, /*!< Reserved for private use */
		PRIVATE_USE_085            = 0xFE3EU, /*!< Reserved for private use */
		PRIVATE_USE_086            = 0xFE3FU, /*!< Reserved for private use */
		PRIVATE_USE_087            = 0xFE40U, /*!< Reserved for private use */
		PRIVATE_USE_088            = 0xFE41U, /*!< Reserved for private use */
		PRIVATE_USE_089            = 0xFE42U, /*!< Reserved for private use */
		PRIVATE_USE_090            = 0xFE43U, /*!< Reserved for private use */
		PRIVATE_USE_091            = 0xFE44U, /*!< Reserved for private use */
		PRIVATE_USE_092            = 0xFE45U, /*!< Reserved for private use */
		PRIVATE_USE_093            = 0xFE46U, /*!< Reserved for private use */
		PRIVATE_USE_094            = 0xFE47U, /*!< Reserved for private use */
		PRIVATE_USE_095            = 0xFE48U, /*!< Reserved for private use */
		PRIVATE_USE_096            = 0xFE49U, /*!< Reserved for private use */
		PRIVATE_USE_097            = 0xFE4AU, /*!< Reserved for private use */
		PRIVATE_USE_098            = 0xFE4BU, /*!< Reserved for private use */
		PRIVATE_USE_099            = 0xFE4CU, /*!< Reserved for private use */
		PRIVATE_USE_100            = 0xFE4DU, /*!< Reserved for private use */
		PRIVATE_USE_101            = 0xFE4EU, /*!< Reserved for private use */
		PRIVATE_USE_102            = 0xFE4FU, /*!< Reserved for private use */
		PRIVATE_USE_103            = 0xFE50U, /*!< Reserved for private use */
		PRIVATE_USE_104            = 0xFE51U, /*!< Reserved for private use */
		PRIVATE_USE_105            = 0xFE52U, /*!< Reserved for private use */
		PRIVATE_USE_106            = 0xFE53U, /*!< Reserved for private use */
		PRIVATE_USE_107            = 0xFE54U, /*!< Reserved for private use */
		PRIVATE_USE_108            = 0xFE55U, /*!< Reserved for private use */
		PRIVATE_USE_109            = 0xFE56U, /*!< Reserved for private use */
		PRIVATE_USE_110            = 0xFE57U, /*!< Reserved for private use */
		PRIVATE_USE_111            = 0xFE58U, /*!< Reserved for private use */
		PRIVATE_USE_112            = 0xFE59U, /*!< Reserved for private use */
		PRIVATE_USE_113            = 0xFE5AU, /*!< Reserved for private use */
		PRIVATE_USE_114            = 0xFE5BU, /*!< Reserved for private use */
		PRIVATE_USE_115            = 0xFE5CU, /*!< Reserved for private use */
		PRIVATE_USE_116            = 0xFE5DU, /*!< Reserved for private use */
		PRIVATE_USE_117            = 0xFE5EU, /*!< Reserved for private use */
		PRIVATE_USE_118            = 0xFE5FU, /*!< Reserved for private use */
		PRIVATE_USE_119            = 0xFE60U, /*!< Reserved for private use */
		PRIVATE_USE_120            = 0xFE61U, /*!< Reserved for private use */
		PRIVATE_USE_121            = 0xFE62U, /*!< Reserved for private use */
		PRIVATE_USE_122            = 0xFE63U, /*!< Reserved for private use */
		PRIVATE_USE_123            = 0xFE64U, /*!< Reserved for private use */
		PRIVATE_USE_124            = 0xFE65U, /*!< Reserved for private use */
		PRIVATE_USE_125            = 0xFE66U, /*!< Reserved for private use */
		PRIVATE_USE_126            = 0xFE67U, /*!< Reserved for private use */
		PRIVATE_USE_127            = 0xFE68U, /*!< Reserved for private use */
		PRIVATE_USE_128            = 0xFE69U, /*!< Reserved for private use */
		PRIVATE_USE_129            = 0xFE6AU, /*!< Reserved for private use */
		PRIVATE_USE_130            = 0xFE6BU, /*!< Reserved for private use */
		PRIVATE_USE_131            = 0xFE6CU, /*!< Reserved for private use */
		PRIVATE_USE_132            = 0xFE6DU, /*!< Reserved for private use */
		PRIVATE_USE_133            = 0xFE6EU, /*!< Reserved for private use */
		PRIVATE_USE_134            = 0xFE6FU, /*!< Reserved for private use */
		PRIVATE_USE_135            = 0xFE70U, /*!< Reserved for private use */
		PRIVATE_USE_136            = 0xFE71U, /*!< Reserved for private use */
		PRIVATE_USE_137            = 0xFE72U, /*!< Reserved for private use */
		PRIVATE_USE_138            = 0xFE73U, /*!< Reserved for private use */
		PRIVATE_USE_139            = 0xFE74U, /*!< Reserved for private use */
		PRIVATE_USE_140            = 0xFE75U, /*!< Reserved for private use */
		PRIVATE_USE_141            = 0xFE76U, /*!< Reserved for private use */
		PRIVATE_USE_142            = 0xFE77U, /*!< Reserved for private use */
		PRIVATE_USE_143            = 0xFE78U, /*!< Reserved for private use */
		PRIVATE_USE_144            = 0xFE79U, /*!< Reserved for private use */
		PRIVATE_USE_145            = 0xFE7AU, /*!< Reserved for private use */
		PRIVATE_USE_146            = 0xFE7BU, /*!< Reserved for private use */
		PRIVATE_USE_147            = 0xFE7CU, /*!< Reserved for private use */
		PRIVATE_USE_148            = 0xFE7DU, /*!< Reserved for private use */
		PRIVATE_USE_149            = 0xFE7EU, /*!< Reserved for private use */
		PRIVATE_USE_150            = 0xFE7FU, /*!< Reserved for private use */
		PRIVATE_USE_151            = 0xFE80U, /*!< Reserved for private use */
		PRIVATE_USE_152            = 0xFE81U, /*!< Reserved for private use */
		PRIVATE_USE_153            = 0xFE82U, /*!< Reserved for private use */
		PRIVATE_USE_154            = 0xFE83U, /*!< Reserved for private use */
		PRIVATE_USE_155            = 0xFE84U, /*!< Reserved for private use */
		PRIVATE_USE_156            = 0xFE85U, /*!< Reserved for private use */
		PRIVATE_USE_157            = 0xFE86U, /*!< Reserved for private use */
		PRIVATE_USE_158            = 0xFE87U, /*!< Reserved for private use */
		PRIVATE_USE_159            = 0xFE88U, /*!< Reserved for private use */
		PRIVATE_USE_160            = 0xFE89U, /*!< Reserved for private use */
		PRIVATE_USE_161            = 0xFE8AU, /*!< Reserved for private use */
		PRIVATE_USE_162            = 0xFE8BU, /*!< Reserved for private use */
		PRIVATE_USE_163            = 0xFE8CU, /*!< Reserved for private use */
		PRIVATE_USE_164            = 0xFE8DU, /*!< Reserved for private use */
		PRIVATE_USE_165            = 0xFE8EU, /*!< Reserved for private use */
		PRIVATE_USE_166            = 0xFE8FU, /*!< Reserved for private use */
		PRIVATE_USE_167            = 0xFE90U, /*!< Reserved for private use */
		PRIVATE_USE_168            = 0xFE91U, /*!< Reserved for private use */
		PRIVATE_USE_169            = 0xFE92U, /*!< Reserved for private use */
		PRIVATE_USE_170            = 0xFE93U, /*!< Reserved for private use */
		PRIVATE_USE_171            = 0xFE94U, /*!< Reserved for private use */
		PRIVATE_USE_172            = 0xFE95U, /*!< Reserved for private use */
		PRIVATE_USE_173            = 0xFE96U, /*!< Reserved for private use */
		PRIVATE_USE_174            = 0xFE97U, /*!< Reserved for private use */
		PRIVATE_USE_175            = 0xFE98U, /*!< Reserved for private use */
		PRIVATE_USE_176            = 0xFE99U, /*!< Reserved for private use */
		PRIVATE_USE_177            = 0xFE9AU, /*!< Reserved for private use */
		PRIVATE_USE_178            = 0xFE9BU, /*!< Reserved for private use */
		PRIVATE_USE_179            = 0xFE9CU, /*!< Reserved for private use */
		PRIVATE_USE_180            = 0xFE9DU, /*!< Reserved for private use */
		PRIVATE_USE_181            = 0xFE9EU, /*!< Reserved for private use */
		PRIVATE_USE_182            = 0xFE9FU, /*!< Reserved for private use */
		PRIVATE_USE_183            = 0xFEA0U, /*!< Reserved for private use */
		PRIVATE_USE_184            = 0xFEA1U, /*!< Reserved for private use */
		PRIVATE_USE_185            = 0xFEA2U, /*!< Reserved for private use */
		PRIVATE_USE_186            = 0xFEA3U, /*!< Reserved for private use */
		PRIVATE_USE_187            = 0xFEA4U, /*!< Reserved for private use */
		PRIVATE_USE_188            = 0xFEA5U, /*!< Reserved for private use */
		PRIVATE_USE_189            = 0xFEA6U, /*!< Reserved for private use */
		PRIVATE_USE_190            = 0xFEA7U, /*!< Reserved for private use */
		PRIVATE_USE_191            = 0xFEA8U, /*!< Reserved for private use */
		PRIVATE_USE_192            = 0xFEA9U, /*!< Reserved for private use */
		PRIVATE_USE_193            = 0xFEAAU, /*!< Reserved for private use */
		PRIVATE_USE_194            = 0xFEABU, /*!< Reserved for private use */
		PRIVATE_USE_195            = 0xFEACU, /*!< Reserved for private use */
		PRIVATE_USE_196            = 0xFEADU, /*!< Reserved for private use */
		PRIVATE_USE_197            = 0xFEAEU, /*!< Reserved for private use */
		PRIVATE_USE_198            = 0xFEAFU, /*!< Reserved for private use */
		PRIVATE_USE_199            = 0xFEB0U, /*!< Reserved for private use */
		PRIVATE_USE_200            = 0xFEB1U, /*!< Reserved for private use */
		PRIVATE_USE_201            = 0xFEB2U, /*!< Reserved for private use */
		PRIVATE_USE_202            = 0xFEB3U, /*!< Reserved for private use */
		PRIVATE_USE_203            = 0xFEB4U, /*!< Reserved for private use */
		PRIVATE_USE_204            = 0xFEB5U, /*!< Reserved for private use */
		PRIVATE_USE_205            = 0xFEB6U, /*!< Reserved for private use */
		PRIVATE_USE_206            = 0xFEB7U, /*!< Reserved for private use */
		PRIVATE_USE_207            = 0xFEB8U, /*!< Reserved for private use */
		PRIVATE_USE_208            = 0xFEB9U, /*!< Reserved for private use */
		PRIVATE_USE_209            = 0xFEBAU, /*!< Reserved for private use */
		PRIVATE_USE_210            = 0xFEBBU, /*!< Reserved for private use */
		PRIVATE_USE_211            = 0xFEBCU, /*!< Reserved for private use */
		PRIVATE_USE_212            = 0xFEBDU, /*!< Reserved for private use */
		PRIVATE_USE_213            = 0xFEBEU, /*!< Reserved for private use */
		PRIVATE_USE_214            = 0xFEBFU, /*!< Reserved for private use */
		PRIVATE_USE_215            = 0xFEC0U, /*!< Reserved for private use */
		PRIVATE_USE_216            = 0xFEC1U, /*!< Reserved for private use */
		PRIVATE_USE_217            = 0xFEC2U, /*!< Reserved for private use */
		PRIVATE_USE_218            = 0xFEC3U, /*!< Reserved for private use */
		PRIVATE_USE_219            = 0xFEC4U, /*!< Reserved for private use */
		PRIVATE_USE_220            = 0xFEC5U, /*!< Reserved for private use */
		PRIVATE_USE_221            = 0xFEC6U, /*!< Reserved for private use */
		PRIVATE_USE_222            = 0xFEC7U, /*!< Reserved for private use */
		PRIVATE_USE_223            = 0xFEC8U, /*!< Reserved for private use */
		PRIVATE_USE_224            = 0xFEC9U, /*!< Reserved for private use */
		PRIVATE_USE_225            = 0xFECAU, /*!< Reserved for private use */
		PRIVATE_USE_226            = 0xFECBU, /*!< Reserved for private use */
		PRIVATE_USE_227            = 0xFECCU, /*!< Reserved for private use */
		PRIVATE_USE_228            = 0xFECDU, /*!< Reserved for private use */
		PRIVATE_USE_229            = 0xFECEU, /*!< Reserved for private use */
		PRIVATE_USE_230            = 0xFECFU, /*!< Reserved for private use */
		PRIVATE_USE_231            = 0xFED0U, /*!< Reserved for private use */
		PRIVATE_USE_232            = 0xFED1U, /*!< Reserved for private use */
		PRIVATE_USE_233            = 0xFED2U, /*!< Reserved for private use */
		PRIVATE_USE_234            = 0xFED3U, /*!< Reserved for private use */
		PRIVATE_USE_235            = 0xFED4U, /*!< Reserved for private use */
		PRIVATE_USE_236            = 0xFED5U, /*!< Reserved for private use */
		PRIVATE_USE_237            = 0xFED6U, /*!< Reserved for private use */
		PRIVATE_USE_238            = 0xFED7U, /*!< Reserved for private use */
		PRIVATE_USE_239            = 0xFED8U, /*!< Reserved for private use */
		PRIVATE_USE_240            = 0xFED9U, /*!< Reserved for private use */
		PRIVATE_USE_241            = 0xFEDAU, /*!< Reserved for private use */
		PRIVATE_USE_242            = 0xFEDBU, /*!< Reserved for private use */
		PRIVATE_USE_243            = 0xFEDCU, /*!< Reserved for private use */
		PRIVATE_USE_244            = 0xFEDDU, /*!< Reserved for private use */
		PRIVATE_USE_245            = 0xFEDEU, /*!< Reserved for private use */
		PRIVATE_USE_246            = 0xFEDFU, /*!< Reserved for private use */
		PRIVATE_USE_247            = 0xFEE0U, /*!< Reserved for private use */
		PRIVATE_USE_248            = 0xFEE1U, /*!< Reserved for private use */
		PRIVATE_USE_249            = 0xFEE2U, /*!< Reserved for private use */
		PRIVATE_USE_250            = 0xFEE3U, /*!< Reserved for private use */
		PRIVATE_USE_251            = 0xFEE4U, /*!< Reserved for private use */
		PRIVATE_USE_252            = 0xFEE5U, /*!< Reserved for private use */
		PRIVATE_USE_253            = 0xFEE6U, /*!< Reserved for private use */
		PRIVATE_USE_254            = 0xFEE7U, /*!< Reserved for private use */
		PRIVATE_USE_255            = 0xFEE8U, /*!< Reserved for private use */
		PRIVATE_USE_256            = 0xFEE9U, /*!< Reserved for private use */
		PRIVATE_USE_257            = 0xFEEAU, /*!< Reserved for private use */
		PRIVATE_USE_258            = 0xFEEBU, /*!< Reserved for private use */
		PRIVATE_USE_259            = 0xFEECU, /*!< Reserved for private use */
		PRIVATE_USE_260            = 0xFEEDU, /*!< Reserved for private use */
		PRIVATE_USE_261            = 0xFEEEU, /*!< Reserved for private use */
		PRIVATE_USE_262            = 0xFEEFU, /*!< Reserved for private use */
		PRIVATE_USE_263            = 0xFEF0U, /*!< Reserved for private use */
		PRIVATE_USE_264            = 0xFEF1U, /*!< Reserved for private use */
		PRIVATE_USE_265            = 0xFEF2U, /*!< Reserved for private use */
		PRIVATE_USE_266            = 0xFEF3U, /*!< Reserved for private use */
		PRIVATE_USE_267            = 0xFEF4U, /*!< Reserved for private use */
		PRIVATE_USE_268            = 0xFEF5U, /*!< Reserved for private use */
		PRIVATE_USE_269            = 0xFEF6U, /*!< Reserved for private use */
		PRIVATE_USE_270            = 0xFEF7U, /*!< Reserved for private use */
		PRIVATE_USE_271            = 0xFEF8U, /*!< Reserved for private use */
		PRIVATE_USE_272            = 0xFEF9U, /*!< Reserved for private use */
		PRIVATE_USE_273            = 0xFEFAU, /*!< Reserved for private use */
		PRIVATE_USE_274            = 0xFEFBU, /*!< Reserved for private use */
		PRIVATE_USE_275            = 0xFEFCU, /*!< Reserved for private use */
		PRIVATE_USE_276            = 0xFEFDU, /*!< Reserved for private use */
		PRIVATE_USE_277            = 0xFEFEU, /*!< Reserved for private use */
		PRIVATE_USE_278            = 0xFEFFU, /*!< Reserved for private use */
		PRIVATE_USE_279            = 0xFF00U, /*!< Reserved for private use */
		PRIVATE_USE_280            = 0xFF01U, /*!< Reserved for private use */
		PRIVATE_USE_281            = 0xFF02U, /*!< Reserved for private use */
		PRIVATE_USE_282            = 0xFF03U, /*!< Reserved for private use */
		PRIVATE_USE_283            = 0xFF04U, /*!< Reserved for private use */
		PRIVATE_USE_284            = 0xFF05U, /*!< Reserved for private use */
		PRIVATE_USE_285            = 0xFF06U, /*!< Reserved for private use */
		PRIVATE_USE_286            = 0xFF07U, /*!< Reserved for private use */
		PRIVATE_USE_287            = 0xFF08U, /*!< Reserved for private use */
		PRIVATE_USE_288            = 0xFF09U, /*!< Reserved for private use */
		PRIVATE_USE_289            = 0xFF0AU, /*!< Reserved for private use */
		PRIVATE_USE_290            = 0xFF0BU, /*!< Reserved for private use */
		PRIVATE_USE_291            = 0xFF0CU, /*!< Reserved for private use */
		PRIVATE_USE_292            = 0xFF0DU, /*!< Reserved for private use */
		PRIVATE_USE_293            = 0xFF0EU, /*!< Reserved for private use */
		PRIVATE_USE_294            = 0xFF0FU, /*!< Reserved for private use */
		PRIVATE_USE_295            = 0xFF10U, /*!< Reserved for private use */
		PRIVATE_USE_296            = 0xFF11U, /*!< Reserved for private use */
		PRIVATE_USE_297            = 0xFF12U, /*!< Reserved for private use */
		PRIVATE_USE_298            = 0xFF13U, /*!< Reserved for private use */
		PRIVATE_USE_299            = 0xFF14U, /*!< Reserved for private use */
		PRIVATE_USE_300            = 0xFF15U, /*!< Reserved for private use */
		PRIVATE_USE_301            = 0xFF16U, /*!< Reserved for private use */
		PRIVATE_USE_302            = 0xFF17U, /*!< Reserved for private use */
		PRIVATE_USE_303            = 0xFF18U, /*!< Reserved for private use */
		PRIVATE_USE_304            = 0xFF19U, /*!< Reserved for private use */
		PRIVATE_USE_305            = 0xFF1AU, /*!< Reserved for private use */
		PRIVATE_USE_306            = 0xFF1BU, /*!< Reserved for private use */
		PRIVATE_USE_307            = 0xFF1CU, /*!< Reserved for private use */
		PRIVATE_USE_308            = 0xFF1DU, /*!< Reserved for private use */
		PRIVATE_USE_309            = 0xFF1EU, /*!< Reserved for private use */
		PRIVATE_USE_310            = 0xFF1FU, /*!< Reserved for private use */
		PRIVATE_USE_311            = 0xFF20U, /*!< Reserved for private use */
		PRIVATE_USE_312            = 0xFF21U, /*!< Reserved for private use */
		PRIVATE_USE_313            = 0xFF22U, /*!< Reserved for private use */
		PRIVATE_USE_314            = 0xFF23U, /*!< Reserved for private use */
		PRIVATE_USE_315            = 0xFF24U, /*!< Reserved for private use */
		PRIVATE_USE_316            = 0xFF25U, /*!< Reserved for private use */
		PRIVATE_USE_317            = 0xFF26U, /*!< Reserved for private use */
		PRIVATE_USE_318            = 0xFF27U, /*!< Reserved for private use */
		PRIVATE_USE_319            = 0xFF28U, /*!< Reserved for private use */
		PRIVATE_USE_320            = 0xFF29U, /*!< Reserved for private use */
		PRIVATE_USE_321            = 0xFF2AU, /*!< Reserved for private use */
		PRIVATE_USE_322            = 0xFF2BU, /*!< Reserved for private use */
		PRIVATE_USE_323            = 0xFF2CU, /*!< Reserved for private use */
		PRIVATE_USE_324            = 0xFF2DU, /*!< Reserved for private use */
		PRIVATE_USE_325            = 0xFF2EU, /*!< Reserved for private use */
		PRIVATE_USE_326            = 0xFF2FU, /*!< Reserved for private use */
		PRIVATE_USE_327            = 0xFF30U, /*!< Reserved for private use */
		PRIVATE_USE_328            = 0xFF31U, /*!< Reserved for private use */
		PRIVATE_USE_329            = 0xFF32U, /*!< Reserved for private use */
		PRIVATE_USE_330            = 0xFF33U, /*!< Reserved for private use */
		PRIVATE_USE_331            = 0xFF34U, /*!< Reserved for private use */
		PRIVATE_USE_332            = 0xFF35U, /*!< Reserved for private use */
		PRIVATE_USE_333            = 0xFF36U, /*!< Reserved for private use */
		PRIVATE_USE_334            = 0xFF37U, /*!< Reserved for private use */
		PRIVATE_USE_335            = 0xFF38U, /*!< Reserved for private use */
		PRIVATE_USE_336            = 0xFF39U, /*!< Reserved for private use */
		PRIVATE_USE_337            = 0xFF3AU, /*!< Reserved for private use */
		PRIVATE_USE_338            = 0xFF3BU, /*!< Reserved for private use */
		PRIVATE_USE_339            = 0xFF3CU, /*!< Reserved for private use */
		PRIVATE_USE_340            = 0xFF3DU, /*!< Reserved for private use */
		PRIVATE_USE_341            = 0xFF3EU, /*!< Reserved for private use */
		PRIVATE_USE_342            = 0xFF3FU, /*!< Reserved for private use */
		PRIVATE_USE_343            = 0xFF40U, /*!< Reserved for private use */
		PRIVATE_USE_344            = 0xFF41U, /*!< Reserved for private use */
		PRIVATE_USE_345            = 0xFF42U, /*!< Reserved for private use */
		PRIVATE_USE_346            = 0xFF43U, /*!< Reserved for private use */
		PRIVATE_USE_347            = 0xFF44U, /*!< Reserved for private use */
		PRIVATE_USE_348            = 0xFF45U, /*!< Reserved for private use */
		PRIVATE_USE_349            = 0xFF46U, /*!< Reserved for private use */
		PRIVATE_USE_350            = 0xFF47U, /*!< Reserved for private use */
		PRIVATE_USE_351            = 0xFF48U, /*!< Reserved for private use */
		PRIVATE_USE_352            = 0xFF49U, /*!< Reserved for private use */
		PRIVATE_USE_353            = 0xFF4AU, /*!< Reserved for private use */
		PRIVATE_USE_354            = 0xFF4BU, /*!< Reserved for private use */
		PRIVATE_USE_355            = 0xFF4CU, /*!< Reserved for private use */
		PRIVATE_USE_356            = 0xFF4DU, /*!< Reserved for private use */
		PRIVATE_USE_357            = 0xFF4EU, /*!< Reserved for private use */
		PRIVATE_USE_358            = 0xFF4FU, /*!< Reserved for private use */
		PRIVATE_USE_359            = 0xFF50U, /*!< Reserved for private use */
		PRIVATE_USE_360            = 0xFF51U, /*!< Reserved for private use */
		PRIVATE_USE_361            = 0xFF52U, /*!< Reserved for private use */
		PRIVATE_USE_362            = 0xFF53U, /*!< Reserved for private use */
		PRIVATE_USE_363            = 0xFF54U, /*!< Reserved for private use */
		PRIVATE_USE_364            = 0xFF55U, /*!< Reserved for private use */
		PRIVATE_USE_365            = 0xFF56U, /*!< Reserved for private use */
		PRIVATE_USE_366            = 0xFF57U, /*!< Reserved for private use */
		PRIVATE_USE_367            = 0xFF58U, /*!< Reserved for private use */
		PRIVATE_USE_368            = 0xFF59U, /*!< Reserved for private use */
		PRIVATE_USE_369            = 0xFF5AU, /*!< Reserved for private use */
		PRIVATE_USE_370            = 0xFF5BU, /*!< Reserved for private use */
		PRIVATE_USE_371            = 0xFF5CU, /*!< Reserved for private use */
		PRIVATE_USE_372            = 0xFF5DU, /*!< Reserved for private use */
		PRIVATE_USE_373            = 0xFF5EU, /*!< Reserved for private use */
		PRIVATE_USE_374            = 0xFF5FU, /*!< Reserved for private use */
		PRIVATE_USE_375            = 0xFF60U, /*!< Reserved for private use */
		PRIVATE_USE_376            = 0xFF61U, /*!< Reserved for private use */
		PRIVATE_USE_377            = 0xFF62U, /*!< Reserved for private use */
		PRIVATE_USE_378            = 0xFF63U, /*!< Reserved for private use */
		PRIVATE_USE_379            = 0xFF64U, /*!< Reserved for private use */
		PRIVATE_USE_380            = 0xFF65U, /*!< Reserved for private use */
		PRIVATE_USE_381            = 0xFF66U, /*!< Reserved for private use */
		PRIVATE_USE_382            = 0xFF67U, /*!< Reserved for private use */
		PRIVATE_USE_383            = 0xFF68U, /*!< Reserved for private use */
		PRIVATE_USE_384            = 0xFF69U, /*!< Reserved for private use */
		PRIVATE_USE_385            = 0xFF6AU, /*!< Reserved for private use */
		PRIVATE_USE_386            = 0xFF6BU, /*!< Reserved for private use */
		PRIVATE_USE_387            = 0xFF6CU, /*!< Reserved for private use */
		PRIVATE_USE_388            = 0xFF6DU, /*!< Reserved for private use */
		PRIVATE_USE_389            = 0xFF6EU, /*!< Reserved for private use */
		PRIVATE_USE_390            = 0xFF6FU, /*!< Reserved for private use */
		PRIVATE_USE_391            = 0xFF70U, /*!< Reserved for private use */
		PRIVATE_USE_392            = 0xFF71U, /*!< Reserved for private use */
		PRIVATE_USE_393            = 0xFF72U, /*!< Reserved for private use */
		PRIVATE_USE_394            = 0xFF73U, /*!< Reserved for private use */
		PRIVATE_USE_395            = 0xFF74U, /*!< Reserved for private use */
		PRIVATE_USE_396            = 0xFF75U, /*!< Reserved for private use */
		PRIVATE_USE_397            = 0xFF76U, /*!< Reserved for private use */
		PRIVATE_USE_398            = 0xFF77U, /*!< Reserved for private use */
		PRIVATE_USE_399            = 0xFF78U, /*!< Reserved for private use */
		PRIVATE_USE_400            = 0xFF79U, /*!< Reserved for private use */
		PRIVATE_USE_401            = 0xFF7AU, /*!< Reserved for private use */
		PRIVATE_USE_402            = 0xFF7BU, /*!< Reserved for private use */
		PRIVATE_USE_403            = 0xFF7CU, /*!< Reserved for private use */
		PRIVATE_USE_404            = 0xFF7DU, /*!< Reserved for private use */
		PRIVATE_USE_405            = 0xFF7EU, /*!< Reserved for private use */
		PRIVATE_USE_406            = 0xFF7FU, /*!< Reserved for private use */
		PRIVATE_USE_407            = 0xFF80U, /*!< Reserved for private use */
		PRIVATE_USE_408            = 0xFF81U, /*!< Reserved for private use */
		PRIVATE_USE_409            = 0xFF82U, /*!< Reserved for private use */
		PRIVATE_USE_410            = 0xFF83U, /*!< Reserved for private use */
		PRIVATE_USE_411            = 0xFF84U, /*!< Reserved for private use */
		PRIVATE_USE_412            = 0xFF85U, /*!< Reserved for private use */
		PRIVATE_USE_413            = 0xFF86U, /*!< Reserved for private use */
		PRIVATE_USE_414            = 0xFF87U, /*!< Reserved for private use */
		PRIVATE_USE_415            = 0xFF88U, /*!< Reserved for private use */
		PRIVATE_USE_416            = 0xFF89U, /*!< Reserved for private use */
		PRIVATE_USE_417            = 0xFF8AU, /*!< Reserved for private use */
		PRIVATE_USE_418            = 0xFF8BU, /*!< Reserved for private use */
		PRIVATE_USE_419            = 0xFF8CU, /*!< Reserved for private use */
		PRIVATE_USE_420            = 0xFF8DU, /*!< Reserved for private use */
		PRIVATE_USE_421            = 0xFF8EU, /*!< Reserved for private use */
		PRIVATE_USE_422            = 0xFF8FU, /*!< Reserved for private use */
		PRIVATE_USE_423            = 0xFF90U, /*!< Reserved for private use */
		PRIVATE_USE_424            = 0xFF91U, /*!< Reserved for private use */
		PRIVATE_USE_425            = 0xFF92U, /*!< Reserved for private use */
		PRIVATE_USE_426            = 0xFF93U, /*!< Reserved for private use */
		PRIVATE_USE_427            = 0xFF94U, /*!< Reserved for private use */
		PRIVATE_USE_428            = 0xFF95U, /*!< Reserved for private use */
		PRIVATE_USE_429            = 0xFF96U, /*!< Reserved for private use */
		PRIVATE_USE_430            = 0xFF97U, /*!< Reserved for private use */
		PRIVATE_USE_431            = 0xFF98U, /*!< Reserved for private use */
		PRIVATE_USE_432            = 0xFF99U, /*!< Reserved for private use */
		PRIVATE_USE_433            = 0xFF9AU, /*!< Reserved for private use */
		PRIVATE_USE_434            = 0xFF9BU, /*!< Reserved for private use */
		PRIVATE_USE_435            = 0xFF9CU, /*!< Reserved for private use */
		PRIVATE_USE_436            = 0xFF9DU, /*!< Reserved for private use */
		PRIVATE_USE_437            = 0xFF9EU, /*!< Reserved for private use */
		PRIVATE_USE_438            = 0xFF9FU, /*!< Reserved for private use */
		PRIVATE_USE_439            = 0xFFA0U, /*!< Reserved for private use */
		PRIVATE_USE_440            = 0xFFA1U, /*!< Reserved for private use */
		PRIVATE_USE_441            = 0xFFA2U, /*!< Reserved for private use */
		PRIVATE_USE_442            = 0xFFA3U, /*!< Reserved for private use */
		PRIVATE_USE_443            = 0xFFA4U, /*!< Reserved for private use */
		PRIVATE_USE_444            = 0xFFA5U, /*!< Reserved for private use */
		PRIVATE_USE_445            = 0xFFA6U, /*!< Reserved for private use */
		PRIVATE_USE_446            = 0xFFA7U, /*!< Reserved for private use */
		PRIVATE_USE_447            = 0xFFA8U, /*!< Reserved for private use */
		PRIVATE_USE_448            = 0xFFA9U, /*!< Reserved for private use */
		PRIVATE_USE_449            = 0xFFAAU, /*!< Reserved for private use */
		PRIVATE_USE_450            = 0xFFABU, /*!< Reserved for private use */
		PRIVATE_USE_451            = 0xFFACU, /*!< Reserved for private use */
		PRIVATE_USE_452            = 0xFFADU, /*!< Reserved for private use */
		PRIVATE_USE_453            = 0xFFAEU, /*!< Reserved for private use */
		PRIVATE_USE_454            = 0xFFAFU, /*!< Reserved for private use */
		PRIVATE_USE_455            = 0xFFB0U, /*!< Reserved for private use */
		PRIVATE_USE_456            = 0xFFB1U, /*!< Reserved for private use */
		PRIVATE_USE_457            = 0xFFB2U, /*!< Reserved for private use */
		PRIVATE_USE_458            = 0xFFB3U, /*!< Reserved for private use */
		PRIVATE_USE_459            = 0xFFB4U, /*!< Reserved for private use */
		PRIVATE_USE_460            = 0xFFB5U, /*!< Reserved for private use */
		PRIVATE_USE_461            = 0xFFB6U, /*!< Reserved for private use */
		PRIVATE_USE_462            = 0xFFB7U, /*!< Reserved for private use */
		PRIVATE_USE_463            = 0xFFB8U, /*!< Reserved for private use */
		PRIVATE_USE_464            = 0xFFB9U, /*!< Reserved for private use */
		PRIVATE_USE_465            = 0xFFBAU, /*!< Reserved for private use */
		PRIVATE_USE_466            = 0xFFBBU, /*!< Reserved for private use */
		PRIVATE_USE_467            = 0xFFBCU, /*!< Reserved for private use */
		PRIVATE_USE_468            = 0xFFBDU, /*!< Reserved for private use */
		PRIVATE_USE_469            = 0xFFBEU, /*!< Reserved for private use */
		PRIVATE_USE_470            = 0xFFBFU, /*!< Reserved for private use */
		PRIVATE_USE_471            = 0xFFC0U, /*!< Reserved for private use */
		PRIVATE_USE_472            = 0xFFC1U, /*!< Reserved for private use */
		PRIVATE_USE_473            = 0xFFC2U, /*!< Reserved for private use */
		PRIVATE_USE_474            = 0xFFC3U, /*!< Reserved for private use */
		PRIVATE_USE_475            = 0xFFC4U, /*!< Reserved for private use */
		PRIVATE_USE_476            = 0xFFC5U, /*!< Reserved for private use */
		PRIVATE_USE_477            = 0xFFC6U, /*!< Reserved for private use */
		PRIVATE_USE_478            = 0xFFC7U, /*!< Reserved for private use */
		PRIVATE_USE_479            = 0xFFC8U, /*!< Reserved for private use */
		PRIVATE_USE_480            = 0xFFC9U, /*!< Reserved for private use */
		PRIVATE_USE_481            = 0xFFCAU, /*!< Reserved for private use */
		PRIVATE_USE_482            = 0xFFCBU, /*!< Reserved for private use */
		PRIVATE_USE_483            = 0xFFCCU, /*!< Reserved for private use */
		PRIVATE_USE_484            = 0xFFCDU, /*!< Reserved for private use */
		PRIVATE_USE_485            = 0xFFCEU, /*!< Reserved for private use */
		PRIVATE_USE_486            = 0xFFCFU, /*!< Reserved for private use */
		PRIVATE_USE_487            = 0xFFD0U, /*!< Reserved for private use */
		PRIVATE_USE_488            = 0xFFD1U, /*!< Reserved for private use */
		PRIVATE_USE_489            = 0xFFD2U, /*!< Reserved for private use */
		PRIVATE_USE_490            = 0xFFD3U, /*!< Reserved for private use */
		PRIVATE_USE_491            = 0xFFD4U, /*!< Reserved for private use */
		PRIVATE_USE_492            = 0xFFD5U, /*!< Reserved for private use */
		PRIVATE_USE_493            = 0xFFD6U, /*!< Reserved for private use */
		PRIVATE_USE_494            = 0xFFD7U, /*!< Reserved for private use */
		PRIVATE_USE_495            = 0xFFD8U, /*!< Reserved for private use */
		PRIVATE_USE_496            = 0xFFD9U, /*!< Reserved for private use */
		PRIVATE_USE_497            = 0xFFDAU, /*!< Reserved for private use */
		PRIVATE_USE_498            = 0xFFDBU, /*!< Reserved for private use */
		PRIVATE_USE_499            = 0xFFDCU, /*!< Reserved for private use */
		PRIVATE_USE_500            = 0xFFDDU, /*!< Reserved for private use */
		PRIVATE_USE_501            = 0xFFDEU, /*!< Reserved for private use */
		PRIVATE_USE_502            = 0xFFDFU, /*!< Reserved for private use */
		PRIVATE_USE_503            = 0xFFE0U, /*!< Reserved for private use */
		PRIVATE_USE_504            = 0xFFE1U, /*!< Reserved for private use */
		PRIVATE_USE_505            = 0xFFE2U, /*!< Reserved for private use */
		PRIVATE_USE_506            = 0xFFE3U, /*!< Reserved for private use */
		PRIVATE_USE_507            = 0xFFE4U, /*!< Reserved for private use */
		PRIVATE_USE_508            = 0xFFE5U, /*!< Reserved for private use */
		PRIVATE_USE_509            = 0xFFE6U, /*!< Reserved for private use */
		PRIVATE_USE_510            = 0xFFE7U, /*!< Reserved for private use */
		PRIVATE_USE_511            = 0xFFE8U, /*!< Reserved for private use */
		PRIVATE_USE_512            = 0xFFE9U, /*!< Reserved for private use */
		PRIVATE_USE_513            = 0xFFEAU, /*!< Reserved for private use */
		PRIVATE_USE_514            = 0xFFEBU, /*!< Reserved for private use */
		PRIVATE_USE_515            = 0xFFECU, /*!< Reserved for private use */
		PRIVATE_USE_516            = 0xFFEDU, /*!< Reserved for private use */
		PRIVATE_USE_517            = 0xFFEEU, /*!< Reserved for private use */
		PRIVATE_USE_518            = 0xFFEFU, /*!< Reserved for private use */
		PRIVATE_USE_519            = 0xFFF0U, /*!< Reserved for private use */
		PRIVATE_USE_520            = 0xFFF1U, /*!< Reserved for private use */
		PRIVATE_USE_521            = 0xFFF2U, /*!< Reserved for private use */
		PRIVATE_USE_522            = 0xFFF3U, /*!< Reserved for private use */
		PRIVATE_USE_523            = 0xFFF4U, /*!< Reserved for private use */
		PRIVATE_USE_524            = 0xFFF5U, /*!< Reserved for private use */
		PRIVATE_USE_525            = 0xFFF6U, /*!< Reserved for private use */
		PRIVATE_USE_526            = 0xFFF7U, /*!< Reserved for private use */
		PRIVATE_USE_527            = 0xFFF8U, /*!< Reserved for private use */
		PRIVATE_USE_528            = 0xFFF9U, /*!< Reserved for private use */
		PRIVATE_USE_529            = 0xFFFAU, /*!< Reserved for private use */
		PRIVATE_USE_530            = 0xFFFBU, /*!< Reserved for private use */
		PRIVATE_USE_531            = 0xFFFCU, /*!< Reserved for private use */
		PRIVATE_USE_532            = 0xFFFDU, /*!< Reserved for private use */
		PRIVATE_USE_533            = 0xFFFEU, /*!< Reserved for private use */
		PRIVATE_USE_534            = 0xFFFFU, /*!< Reserved for private use */
		PRIVATE_USE_END            = 0xFFFFU, /*!< End of private use range */
	};

	[[nodiscard]]
	constexpr bool is_private(const linktype_t& type) noexcept {
		constexpr static auto range_beg{static_cast<std::uint16_t>(linktype_t::PRIVATE_USE_BEG)};
		constexpr static auto range_end{static_cast<std::uint16_t>(linktype_t::PRIVATE_USE_BEG)};
		const auto value{static_cast<std::uint16_t>(type)};
		return (value >= range_beg) && (value <= range_end);
	}

	PANKO_API const std::unordered_map<linktype_t, std::string_view> linktype_names;
}

#endif /* PANKO_CAPTURE_LINKTYPE_HH */
